# Generated by Django 4.2.3 on 2023-08-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
